PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX BIO:  <http://www.purl.obolibrary.org/BIO/>


SELECT ?deviceLabel ?manufacturer ?profile
WHERE {
    ?breastImplantDevice rdfs:label "breast implant device" .

    ?device rdfs:label ?deviceLabel .
    ?device rdfs:subClassOf* ?breastImplantDevice .

    # Filter all intermediate classes
    filter not exists {
        ?subtype rdfs:subClassOf ?device .
    }

    # Object Properties
    ?hasManufacturer rdfs:label "has manufacturer" .

    VALUES ?objectProps {
        "has manufacturer"
        "has profile"
    }

    ?device rdfs:subClassOf* [
        a owl:Restriction ;
        owl:onProperty ?objectProps ;
        owl:someValuesFrom ?description
    ]
    ?manufacturerIRI rdfs:label ?manufacturer .
    ?profileIRI rdfs:label ?profile .
}
